# Generated by Django 5.0.6 on 2024-06-18 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('birthday', models.DateField()),
                ('type_document', models.CharField(choices=[('dni', 'dni'), ('passsport', 'passport')], max_length=10)),
                ('number_document', models.CharField(max_length=12, unique=True)),
                ('phone_code', models.IntegerField()),
                ('phone_number', models.IntegerField(unique=True)),
                ('email_address', models.EmailField(max_length=45, unique=True)),
                ('home_address', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('birthday', models.DateField()),
                ('type_document', models.CharField(choices=[('dni', 'dni'), ('passsport', 'passport')], max_length=10)),
                ('number_document', models.CharField(max_length=12, unique=True)),
                ('phone_code', models.IntegerField()),
                ('phone_number', models.IntegerField(unique=True)),
                ('email_address', models.EmailField(max_length=45, unique=True)),
                ('home_address', models.CharField(max_length=45, unique=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
