# Generated by Django 5.0.6 on 2024-06-18 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('state', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=45)),
                ('content_text', models.TextField()),
                ('content_media', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PostNewsLetterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletteremail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Newsletter.newsletteremail')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Newsletter.post')),
            ],
            options={
                'unique_together': {('post_id', 'newsletteremail_id')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='many',
            field=models.ManyToManyField(through='Newsletter.PostNewsLetterEmail', to='Newsletter.newsletteremail'),
        ),
    ]
