# Generated by Django 5.0.6 on 2024-06-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_media',
            field=models.FileField(upload_to='posts/'),
        ),
    ]
