# Generated by Django 5.0.6 on 2024-06-18 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('collegiate_code', models.CharField(max_length=45, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('birthday', models.DateField()),
                ('type_document', models.CharField(choices=[('dni', 'dni'), ('passsport', 'passport')], max_length=45)),
                ('number_document', models.CharField(max_length=12)),
                ('phone_code', models.IntegerField()),
                ('phone_number', models.IntegerField(unique=True)),
                ('email_address', models.CharField(max_length=45, unique=True)),
                ('home_address', models.CharField(max_length=45)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('symptoms', models.TextField()),
                ('observation', models.TextField()),
                ('prescription', models.TextField()),
                ('report', models.BinaryField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultation.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultation.doctor')),
                ('speciality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultation.speciality')),
            ],
            options={
                'unique_together': {('doctor_id', 'speciality_id')},
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='many',
            field=models.ManyToManyField(through='Consultation.DoctorSpeciality', to='Consultation.speciality'),
        ),
    ]
