# Generated by Django 5.0.6 on 2024-06-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0002_alter_consultation_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
