# Generated by Django 5.0.6 on 2024-07-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0003_alter_consultation_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
